package com.slack.bot.infrastructure.common;

public enum BoxDetailOwnerType {
    SLACK_INTERACTION_INBOX,
    SLACK_INTERACTION_INBOX_HISTORY,
    SLACK_NOTIFICATION_OUTBOX,
    SLACK_NOTIFICATION_OUTBOX_HISTORY,
    REVIEW_REQUEST_INBOX,
    REVIEW_REQUEST_INBOX_HISTORY,
    REVIEW_NOTIFICATION_OUTBOX,
    REVIEW_NOTIFICATION_OUTBOX_HISTORY
}
