DROP TABLE IF EXISTS test_audit_entity;
DROP TABLE IF EXISTS review_reminders;
DROP TABLE IF EXISTS review_reservation_interactions;
DROP TABLE IF EXISTS review_reservations;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS oauth_verification_states;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS access_links;
DROP TABLE IF EXISTS access_link_sequences;
DROP TABLE IF EXISTS notification_settings;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS slack_interaction_inbox;
DROP TABLE IF EXISTS slack_notification_outbox;

CREATE TABLE IF NOT EXISTS test_audit_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    access_token VARCHAR(255) NOT NULL,
    bot_user_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS oauth_verification_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    state VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id VARCHAR(255),
    slack_user_id VARCHAR(255),
    display_name VARCHAR(255),
    github_id VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_project_members_team_slack UNIQUE (team_id, slack_user_id)
);

CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id VARCHAR(255),
    slack_channel_id VARCHAR(255),
    channel_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS access_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_key VARCHAR(255) NOT NULL UNIQUE,
    project_member_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS access_link_sequences (
    id BIGINT PRIMARY KEY,
    next_value BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255) NOT NULL,
    api_key VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_member_id BIGINT NOT NULL UNIQUE,
    delivery_space VARCHAR(255) NOT NULL,
    reservation_canceled_confirmation_enabled BOOLEAN NOT NULL,
    reservation_channel_ephemeral_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    review_reminder_enabled BOOLEAN NOT NULL,
    pull_request_mention_enabled BOOLEAN NOT NULL,
    review_completed_enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS review_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    pull_request_id BIGINT NOT NULL,
    pull_request_number INT NOT NULL,
    pull_request_title VARCHAR(500) NOT NULL,
    pull_request_url VARCHAR(500) NOT NULL,
    author_slack_id VARCHAR(255) NOT NULL,
    reviewer_slack_id VARCHAR(255) NOT NULL,
    scheduled_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS review_reservation_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    pull_request_id BIGINT NOT NULL,
    reviewer_slack_id VARCHAR(255) NOT NULL,
    review_scheduled_at TIMESTAMP(6),
    review_time_selected_at TIMESTAMP(6),
    pull_request_notified_at TIMESTAMP(6),
    schedule_cancel_count INT NOT NULL,
    schedule_change_count INT NOT NULL,
    review_fulfilled BOOLEAN NOT NULL,
    CONSTRAINT uk_review_reservation_interactions_review_key UNIQUE (
        team_id,
        project_id,
        pull_request_id,
        reviewer_slack_id
    )
);

CREATE TABLE IF NOT EXISTS review_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    reservation_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP(6) NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    pull_request_author_slack_id VARCHAR(255) NOT NULL,
    reviewer_slack_id VARCHAR(255) NOT NULL,
    pull_request_url VARCHAR(500) NOT NULL,
    pull_request_title VARCHAR(500) NOT NULL,
    fired_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS slack_interaction_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    interaction_type VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    payload_json CLOB NOT NULL,
    status VARCHAR(20) NOT NULL,
    processing_attempt INT NOT NULL,
    processing_started_at TIMESTAMP(6),
    processed_at TIMESTAMP(6),
    failed_at TIMESTAMP(6),
    failure_reason VARCHAR(500),
    failure_type VARCHAR(40),
    CONSTRAINT uk_slack_interaction_inbox_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS slack_notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    message_type VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    text CLOB,
    blocks_json CLOB,
    fallback_text VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    processing_attempt INT NOT NULL,
    processing_started_at TIMESTAMP(6),
    sent_at TIMESTAMP(6),
    failed_at TIMESTAMP(6),
    failure_reason VARCHAR(500),
    failure_type VARCHAR(40),
    CONSTRAINT uk_slack_notification_outbox_idempotency_key UNIQUE (idempotency_key)
);
