DROP TABLE IF EXISTS test_audit_entity;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS oauth_verification_states;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS access_links;
DROP TABLE IF EXISTS access_link_sequences;

CREATE TABLE IF NOT EXISTS test_audit_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    access_token VARCHAR(255) NOT NULL,
    bot_user_id VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_verification_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    state VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id VARCHAR(255),
    slack_user_id VARCHAR(255),
    display_name VARCHAR(255),
    github_id VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key VARCHAR(255),
    team_id VARCHAR(255),
    channel_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS access_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_key VARCHAR(255) NOT NULL UNIQUE,
    project_member_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS access_link_sequences (
    id BIGINT PRIMARY KEY,
    next_value BIGINT NOT NULL
);
